### ISSUE TITLE
Could not finish active span, missing active scope

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-core#31]
https://github.com/auxmoney/OpentracingBundle-core/blob/d87e39d05ea7af484b659619d8db09e21919a174/EventListener/FinishControllerSpanSubscriber.php#L29-L34

This event listener is bound to the 'kernel.response' event, but the event listener that starts the corresponding span is bound to the 'kernel.controller' event.

https://github.com/auxmoney/OpentracingBundle-core/blob/d87e39d05ea7af484b659619d8db09e21919a174/EventListener/StartControllerSpanSubscriber.php#L23-L28

In some cases, the response is sent before the controller is reached (when an exception is thrown between the request event and the controller event), making the finish span failing with the message `Auxmoney\OpentracingBundle\Service\TracingService: could not finish active span, missing active scope`.

**Comment by eddycharly** [comment]
@cawolf I tried to merge the start and finish controller span event listeners and maintain a counter of `kernel.controller` events.
Definitely not perfect, especially with sub requests, but it solves the simple case.

https://github.com/eddycharly/OpentracingBundle-core/commit/cb24b9822bf98d5a56c1dc9932994365d100cb12

What do you think ?

**Comment by cawolf** [comment]
Interesting case, can you provide a gist / demo project to reproduce this behaviour? I'm curious how this happens in the symfony flow.

Your possible solution leads to possibly missing tracing information, such as the response code - a complete HTTP response can be invisible now. If we understand the source of the bug, we can maybe come up with a solution which conserves this information.

**Comment by eddycharly** [comment]
This happens when trying to access application pages that require to be logged in.

The logged in check happens before invoking the controller and returns a 302 to the login page when the user is not logged in (typically a user clicking on a link in an email).

I will try to make a simple demo of this tomorrow if you want.

**Comment by cawolf** [comment]
Ah, good point. From your perspective, what would be the desired outcome:
* have a full trace consisting of 1 span
* have a full trace consisting of 2 spans
* have no trace, but without a warning in the logs
?

No, I don't need the demo for this situtation anymore.

**Comment by eddycharly** [comment]
In my opinion a full trace consisting of 1 span sounds pretty good. What would go in the second span ?
Also, i don't see a good reason for not tracing the request.

Please, keep the logs, it's pretty useful to detect inconsistent behavior.

**Comment by cawolf** [comment]
Ok, right now, witrh my demo setup, I get a trace for the failed access to a secured route, which consists of 1 span. The only thing which is bothering you is the logger warning, right?

**Comment by eddycharly** [comment]
Yes, we collect warnings in sentry and sentry keeps crying since i deployed in production yesterday.

**Comment by eddycharly** [comment]
Also, i consider it an issue because the root span is finished on the wrong event (`kernel.response` instead of `kernel.finish_request` in this case).

**Comment by eddycharly** [comment]
@cawolf do you have an idea on how to solve the issue ?
I could help if you don't have the time to work on it if you can provide a description of the solution you would like to see implemented.

**Comment by cawolf** [comment]
We just discussed the issue and your proposed solution seems to be the best approach. Could you please open a pull request?

**Comment by eddycharly** [comment]
Sure, I would like to try to improve the solution tho.Maybe keeping a stack identifying the request and trying to make a match in the onResponse handler to prevent closing the wrong span.

**Comment by cawolf** [comment]
I would not recommend doing this. This was the one big thing on our "do not do" list, keeping track of open spans in general. As a workaround for this specific problem, it is ok, though.

As a user, you are in charge of matching the opening and closing of spans, and our bundle is just exposing the API to do so. But we explicitely decided against being more than an API and automatic spanning functionality in the sense of validating the manual spanning a user has implemented.

**Comment by eddycharly** [comment]
Checking if the request has the `_controller` attribute should do the trick.

**Comment by cawolf** [comment]
This is even better!

**Comment by eddycharly** [comment]
PR opened https://github.com/auxmoney/OpentracingBundle-core/pull/32

**Comment by eddycharly** [comment]
Just tried it and it didn't solve the issue :(
I'm afraid the `_controller` attribute is already set when the `AccessDeniedException` is thrown.
Shall we introduce an attribute we own ? something like `auxmoney_controller` ?
