### ISSUE TITLE
Add ERROR tag ?

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-core#35]
Why not add `$this->tracing->setTagOfActiveSpan(ERROR, true);` in the following locations:

- here if status code >= 500
https://github.com/auxmoney/OpentracingBundle-core/blob/a3ab2e3a4951de76a1ea1aedd2fd4235d0dc8038/Internal/Decorator/RequestSpanningService.php#L31-L34

- here
https://github.com/auxmoney/OpentracingBundle-core/blob/3d68ac428ac9d62daf9d1ab578a2e86323687a0e/EventListener/ExceptionLogSubscriber.php#L37-L49

- here if status code >= 500
https://github.com/auxmoney/OpentracingBundle-core/blob/a3ab2e3a4951de76a1ea1aedd2fd4235d0dc8038/EventListener/FinishControllerSpanSubscriber.php#L40-L49

- here if exit code != 0
https://github.com/auxmoney/OpentracingBundle-core/blob/a3ab2e3a4951de76a1ea1aedd2fd4235d0dc8038/EventListener/FinishCommandSpanSubscriber.php#L33-L38

- here if status code >= 500
https://github.com/auxmoney/OpentracingBundle-core/blob/a3ab2e3a4951de76a1ea1aedd2fd4235d0dc8038/EventListener/FinishRootSpanSubscriber.php#L33-L41

**Comment by cawolf** [comment]
No reason not to do it, so let's do it. :+1: 

For HTTP requests, I would argue that even everything above `400` is an error, from the application's point of view.

**Comment by eddycharly** [comment]
IMHO http 4xx status codes do not necessarily mean an error as technically all went fine.
Let's take a HEAD request for example, it's not an error when a HEAD request returns a 404.

**Comment by mmross** [comment]
i agree with you @eddycharly. The HTTP Return Status Code 404 is not for an technically error.
only a point to think about, to create a list of status codes above 400 which are not for thoses errors?

**Comment by MollocH** [comment]
IMO a HEAD request should not be considered different from a GET request. One could argue that a 404 as HEAD is as expected or unexpected as for the GET request.

In this case I would follow the guzzle rule itself: >=400 throws a ClientException and >= 500 throws a ServerException and therefore everything >= 400 should be considered an error

**Comment by eddycharly** [comment]
For status codes >= 500 we are sure it's an error.

For status codes >= 400 and < 500, my feeling is that it should be the end user's responsibility to set the error flag as needed.
I mean, there will always be a debate around this choice so leaving the responsibility to the end user makes sense i guess.

Anyway that's just my personal opinion, if the consensus is to treat 4xx status codes as errors i will change the rule.

**Comment by cawolf** [comment]
I think Guzzle's implementation is right here, because according to the [RFC](https://tools.ietf.org/html/rfc7231#section-6.5), everything above 399 is considered an error (or a potential error). And our plugin should not try to implement the next solution on how to interpret these debatable 404 codes, which may be fine under certain circumstances.

**Comment by eddycharly** [comment]
@cawolf are you suggesting we should follow the Guzzle approach and treat all status codes >= 400 as errors ?

**Comment by cawolf** [comment]
Yes, exactly. I mean, we are talking about a tag in a span in a trace, not hard application logic. We should align with the mainstream here.

**Comment by eddycharly** [comment]
Alrite, i will update the PR.
Thanks.

**Comment by cawolf** [comment]
:tada: This PR is included in version 0.6.5 :tada:
