### ISSUE TITLE
support PHP 8

### ISSUE THREAD

**Issue by cawolf** [auxmoney/OpentracingBundle-core#62]
Can only be tackled after #54 and #55 are resolved.

**Comment by ThisIsAreku** [comment]
Any ETA on this issue ? It seems that #54 and #55 are resolved

**Comment by cawolf** [comment]
This is the next step to take, even before deprecating Symfony 3.4 and enabling Symfony 6.0. 

We already checked the compatibility of all packages and see no problem there, so we will start implementing as soon as there is some free time.

**Comment by cawolf** [comment]
Unfortunately, our check did not include the dev-dependencies. We need to move away from Phpunit 7.5 to at least Phpunit 8.5, but will instead move directly to the current version 9.5.

We hope to migrate Phpunit very swiftly.

**Comment by cawolf** [comment]
The upgrade to Phpunit 9.5 is done. We will probably start upgrading to PHP 8 next week.

**Comment by cawolf** [comment]
All active plugins are updated and usable for PHP versions ^7.4 and ^8.0.

The next issue being #75, we will drop support for Symfony 3.4 and enable Symfony 6.0 support.
