### ISSUE TITLE
How to extract

### ISSUE THREAD

**Issue by stevenbrookes** [auxmoney/OpentracingBundle-core#71]
HI

I need to put the span context into a queuing system and then continue the span when the message comes off the queue.

I can get the span context fine using tracing->injectTracingHeadersIntoCarrier() 

But I've searched around and can't find how to do the extract part so that Tracing knows I want to continue using this span context.  Any pointers on how to do that?

Many thanks

Steve

**Comment by cawolf** [comment]
Hi @stevenbrookes ,

you can have a look at either of our RabbitMQ plugins for an implementation example, e.g. our [Producer implementation](https://github.com/auxmoney/OpentracingBundle-amqplib-RabbitMq/blob/v0.1.3/Producer/Producer.php#L58-L64)

Essentially, you can inject the tracing headers into a plain array and pass them into the message as headers.

On the consuming side, we [extract the context](https://github.com/auxmoney/OpentracingBundle-amqplib-RabbitMq/blob/v0.1.3/EventSubscriber/BeforeMessageProcessingSubscriber.php#L68-L71) from the headers and [start](https://github.com/auxmoney/OpentracingBundle-amqplib-RabbitMq/blob/v0.1.3/EventSubscriber/BeforeMessageProcessingSubscriber.php#L44-L47) (and later [stop](https://github.com/auxmoney/OpentracingBundle-amqplib-RabbitMq/blob/v0.1.3/EventSubscriber/AfterMessageProcessingSubscriber.php#L37)) this span with our convenience functions from the core plugin.

Did this explanation help a little?

**Comment by cawolf** [comment]
Hi @stevenbrookes ,

as we do not know how to tackle your question in another way, we close this issue for now.

Best, @cawolf
